# Site settings
title: heheda
header-img: "img/autumn2.jpg"
tagline: Just another engineer
description:  
baseurl: https://liangli2718.github.io
# url: "http://localhost:4000"

url: https://liangli2718.github.io
enforce_ssl: https://liangli2718.github.io

# About/contact
owner: 
  name: Liang Li
  email: liangli2718@gmail.com
  bio:

# Data
gavatar: https://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

# douban_username:
# twitter_username: 
github_username: liangli2718  
# facebook_username:  
# weibo_username:  
# zhihu_username:  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

plugins: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Amsterdam


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Liang"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# # Comments 
# comments :
#   provider :
#   duoshuo :
#     short_name :
#   disqus :
#       short_name :

# Analytics and webmaster tools stuff goes here
google_analytics:
# UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
